import re
import os
import asyncio
import httpx
import yt_dlp
from pathlib import Path
from config import TEMP_DIR, BASE_DIR

def extract_bvid(url_or_bvid: str) -> str:
    """
    提取 URL 或输入字符串中的 BVID
    """
    url_or_bvid = url_or_bvid.strip()
    # 匹配 B 站 BV 号的正则表达式 (BV 开头加 10 位 Base58 字符)
    match = re.search(r'(BV[a-zA-Z0-9]{10})', url_or_bvid, re.IGNORECASE)
    if match:
        return match.group(1)
    raise ValueError("未检测到有效的 Bilibili BV 号或链接，请检查输入")

async def get_video_metadata_api(bvid: str) -> dict:
    """
    通过 B 站官方网页端 API 获取视频标题与描述（最快、最稳定）
    """
    url = f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://www.bilibili.com/"
    }
    
    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.get(url, headers=headers)
        if response.status_code == 200:
            res_json = response.json()
            if res_json.get("code") == 0:
                data = res_json.get("data", {})
                return {
                    "title": data.get("title", "未命名视频"),
                    "description": data.get("desc", "无简介")
                }
    raise Exception("Bilibili API 请求失败")

async def get_video_metadata_ytdlp(bvid: str) -> dict:
    """
    作为备选方案，使用 yt-dlp 提取视频元数据
    """
    url = f"https://www.bilibili.com/video/{bvid}"
    ydl_opts = {
        'extract_flat': True,
        'quiet': True,
        'noplaylist': True,
        'http_headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Referer': 'https://www.bilibili.com/',
        }
    }
    
    def run_extract():
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return {
                "title": info.get("title", "未命名视频"),
                "description": info.get("description", "无简介")
            }
            
    return await asyncio.to_thread(run_extract)

async def get_video_metadata(bvid: str) -> dict:
    """
    综合获取元数据，包含降级容错机制
    """
    try:
        return await get_video_metadata_api(bvid)
    except Exception:
        # 降级到 yt-dlp 提取
        try:
            return await get_video_metadata_ytdlp(bvid)
        except Exception as e:
            raise Exception(f"解析视频元数据失败: {str(e)}")

def convert_cookies_json_to_text(json_path: Path, txt_path: Path):
    """
    将 JSON 格式的 cookies 转换为 yt-dlp 原生支持的 Netscape text 格式
    """
    import json
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            cookies = json.load(f)
        
        if not isinstance(cookies, list):
            print(" -> [Cookies Convert] 格式错误：cookies.json 的根节点不是 JSON 数组")
            return
            
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is automatically generated by bili2text. Do not edit.\n\n")
            
            for c in cookies:
                domain = c.get("domain", "")
                if not domain:
                    continue
                flag = "FALSE" if c.get("hostOnly", False) else "TRUE"
                path = c.get("path", "/")
                secure = "TRUE" if c.get("secure", False) else "FALSE"
                
                expiration = c.get("expirationDate")
                if expiration is None:
                    expiration = 2000000000
                else:
                    expiration = int(expiration)
                    
                name = c.get("name", "")
                value = c.get("value", "")
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
        print(f" -> [Cookies Convert] 成功将 cookies.json 转换为标准 Netscape 格式的 cookies.txt")
    except Exception as e:
        print(f" -> [Cookies Convert] 转换 cookies.json 失败: {e}")

async def download_audio(bvid: str, progress_callback, check_cancel_callback=None) -> str:
    """
    下载 B 站视频的纯音频轨，保存为临时的 .m4a 格式
    progress_callback 接受 0-100 的整数，表示下载进度
    check_cancel_callback 是一个无参函数，如果返回 True 将中断下载
    """
    url = f"https://www.bilibili.com/video/{bvid}"
    # yt-dlp 下载模板，保存到临时目录
    # 注意用 bvid 作为文件名，避免重名冲突
    output_template = str(TEMP_DIR / f"{bvid}.%(ext)s")
    
    def ydl_progress_hook(d):
        if check_cancel_callback and check_cancel_callback():
            raise Exception("TASK_CANCELLED_BY_USER")
            
        if d['status'] == 'downloading':
            total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
            downloaded = d.get('downloaded_bytes') or 0
            if total > 0:
                percent = int(downloaded / total * 100)
                # 回传进度
                progress_callback(percent)
        elif d['status'] == 'finished':
            progress_callback(100)

    ydl_opts = {
        'format': 'bestaudio/best',  # 提取最高画质纯音频
        'outtmpl': output_template,
        'noplaylist': True,
        'quiet': True,
        'progress_hooks': [ydl_progress_hook],
        'retries': 10,  # 网络波动时增加重试次数
        'fragment_retries': 10,
        'nocheckcertificate': True,  # 禁用证书校验，解决代理软件伪造/解密带来的 SSL EOF 错误
        'extractor_args': {
            'bilibili': {
                'prefer_http': True  # 强制 B 站媒体流走 HTTP 而不是 HTTPS，彻底绕开 SSL 协议断开限制
            }
        },
        'http_headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Referer': 'https://www.bilibili.com/',
            'Origin': 'https://www.bilibili.com',
        }
    }

    # 自动兼容 cookies.json。若 json 比 txt 新或 txt 不存在，则先转换它
    cookies_json_path = BASE_DIR / "cookies.json"
    cookies_txt_path = BASE_DIR / "cookies.txt"
    
    if cookies_json_path.exists():
        need_convert = False
        if not cookies_txt_path.exists():
            need_convert = True
        else:
            try:
                if os.path.getmtime(cookies_json_path) > os.path.getmtime(cookies_txt_path):
                    need_convert = True
            except Exception:
                need_convert = True
                
        if need_convert:
            convert_cookies_json_to_text(cookies_json_path, cookies_txt_path)

    # 如果项目根目录下有 cookies.txt，自动加载以避开 B 站对机房公网 IP 限制的 412 Precondition Failed / 人机验证
    if cookies_txt_path.exists():
        ydl_opts['cookiefile'] = str(cookies_txt_path)
        print(" -> [BiliBili Download] 检测并自动加载 Netscape 格式 cookies.txt 启用登录态下载。")

    def run_download():
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            # 获取实际保存的扩展名
            ext = info.get('ext', 'm4a')
            filepath = TEMP_DIR / f"{bvid}.{ext}"
            return str(filepath)

    return await asyncio.to_thread(run_download)

def delete_temp_file(filepath: str):
    """
    销毁下载的临时文件，确保无痕管理
    """
    try:
        if filepath and os.path.exists(filepath):
            os.remove(filepath)
            print(f"临时音频文件已销毁: {filepath}")
    except Exception as e:
        print(f"销毁临时音频文件失败 {filepath}: {e}")
